dataset:
  paths:
    input: ./dataset/test_input_field_fill.mat
    target: ./dataset/test_target_field_fill.mat
  format:
    inputs: [X, Y, U, V]  # Input variable names.
    output: h             # Target variable name.

test:
  batch_size: 1           # Number of samples per batch.
  model_path: ./logs/20240403-1734/model/checkpoint_epoch_1000.pth
  results_dir: ./dataset/

environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
