dataset:
  paths:
    input: ./dataset/1107/test_mike_input.mat
    target: ./dataset/1107/test_mike_target.mat
  channels:
    input: 5
    output: 1

test:
  batch_size: 1           # Number of samples per batch.
  model_path: ./logs/20241107-1752/model/best.pth
  results_dir: ./logs/20241107-1752/

environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
