dataset:
  paths:
    input: ./dataset/test_input2013.mat
    target: ./dataset/test_target2013.mat
  channels:
    input: 5
    output: 1

test:
  batch_size: 1           # Number of samples per batch.
  model_path: ./logs/20240424-1512/model/best.pth
  results_dir: ./logs/20240424-1512/

environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.