dataset:
  paths:
    input: ./dataset/test_input_April11.mat
    target: ./dataset/test_target_April11.mat
  format:
    inputs: [X, Y, U, V]  # Input variable names.
    output: [U, V]             # Target variable name.

test:
  batch_size: 1           # Number of samples per batch.
  model_path: ./logs/20240411-2331/model/checkpoint_epoch_600.pth
  results_dir: ./dataset/

environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
