dataset:
  paths:
    input: ./dataset/test_input_uv.mat
    target: ./dataset/test_target_uv.mat
  channels:
    input: 4
    output: 2

test:
  batch_size: 1           # Number of samples per batch.
  model_path: ./logs/20240425-1407/model/best.pth
  results_dir: ./logs/20240425-1407/

environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
