dataset:
  paths:
    input: ./dataset/readyToTrainData/test_input_all.mat
    target: ./dataset/readyToTrainData/test_target_all.mat
  channels:
    input: 2
    output: 1

test:
  batch_size: 1           # Number of samples per batch.
  model_path: ./logs/20241114-1835/model/best.pth
  results_dir: ./logs/20241114-1835/

environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
