dataset:
  paths:
    input: ./dataset/train_input.mat
    target: ./dataset/train_target.mat
  channels:
    input: 5
    output: 1

training:
  max_epoch: 2000        # Total number of training epochs.
  batch_size: 2           # Number of samples per batch.
  regularization: 0.5    # Regularization factor for model training.
  learning_rate: 0.0002    # Initial learning rate.
  scheduler:
    step_size: 200        # Learning rate scheduler step size.
    gamma: 0.8            # Learning rate decay factor.
  physics: True
  fidelity: True
  phy_loss_coef: 1000
  fid_loss_coef: 1
  patience: 1000
  
environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
  logging: True           # Enable logging of training process.

physics:
  dx: 3.2
  dy: 3.2
  huber_delta: 0.25
