dataset:
  paths:
    input: ./dataset/train_input2.mat
    target: ./dataset/train_target.mat
  format:
    inputs: [U, V]  # Input variable names.
    output: h             # Target variable name.
  output_size: 256        # Size of the output variable.

training:
  max_epoch: 1000        # Total number of training epochs.
  batch_size: 2           # Number of samples per batch.
  learning_rate: 0.001    # Initial learning rate.
  regularization: 0.01    # Regularization factor for model training.
  scheduler:
    step_size: 200        # Learning rate scheduler step size.
    gamma: 0.5            # Learning rate decay factor.
  physics: True
  fidelity: True
  patience: 1000
  
environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
  logging: True           # Enable logging of training process.
