dataset:
  paths:
    input: ./dataset/train_input_h_200m.mat
    target: ./dataset/train_target_h_200m.mat
  channels:
    input: 5
    output: 1

training:
  max_epoch: 1000         # Total number of training epochs.
  batch_size: 2           # Number of samples per batch.
  regularization: 0.1     # Regularization factor for model training.
  learning_rate: 0.0002   # Initial learning rate.
  scheduler:
    step_size: 200        # Learning rate scheduler step size.
    gamma: 0.8            # Learning rate decay factor.
  fidelity: True
  fid_loss_coef: 1
  physics: True
  phy_loss_coef: 10
  
environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
  logging: True           # Enable logging of training process.

physics:
  dx: 3.2
  dy: 3.2
  huber_delta: 1.0
