dataset:
  paths:
    input: ./dataset/train_input_field_rnd.mat
    target: ./dataset/train_target_field_rnd.mat
  format:
    inputs: [X, Y, U, V]  # Input variable names.
    output: h             # Target variable name.
  output_size: 256        # Size of the output variable.

training:
  max_epoch: 1000        # Total number of training epochs.
  batch_size: 2           # Number of samples per batch.
  regularization: 0.02    # Regularization factor for model training.
  learning_rate: 0.0005    # Initial learning rate.
  scheduler:
    step_size: 100        # Learning rate scheduler step size.
    gamma: 0.8            # Learning rate decay factor.
  physics: True
  fidelity: True
  patience: 1000
  
environment:
  gpu: 0                  # Identifier for the GPU to use.
  seed: 1234              # Seed for random number generation.
  logging: True           # Enable logging of training process.

physics:
  dx: 3.2
  dy: 3.2
  huber_delta: 0.25
