dataset:
  input_path: ./dataset/input_data.mat
  target_path: ./dataset/target_data.mat
  inputs:
    - name: X
      requires_grad: false
    - name: Y
      requires_grad: false
    - name: U
      requires_grad: false
    - name: V
      requires_grad: false
  outputs:
    - h
  output_size: 256


initialization:
  gpu: 0              # GPU card id.
  seed: 1234          # Random seed.
  log: true           # Save the training results.
  lr: 0.00001         # Learning rate, default 1e-5.
  lu: 0.5             # Regularization factor, default 0.5.
  scheduler_step: 100 # Scheduler step size. Default 25.
  total_epochs: 10   # Total running epochs. Default 100.
  batch_size: 2           # Max frames that will be sampled as a batch.

  data_path: ./data/
